# .github/workflows/deploy.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]    # Ajusta el nombre de la rama según tu proyecto

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18         # Cambia la versión si lo necesitas

      - name: Install dependencies
        run: npm ci
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: Build project
        run: npm run build
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build       # Ajusta a la carpeta generada por tu build
